spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cngbgrymmoi7.us-east-1.rds.amazonaws.com:3305/database-1?useUnicode=true&characterEncoding=UTF-8
    username: hunil
    password: hunil3751
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: ture
logging:
  level:
    org.hibernate.SQL: debug