spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://joindeveloper.crnv58a7zwkg.ap-northeast-2.rds.amazonaws.com:3306/aws
    username: hunil
    password: hunil3751
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: ture
logging:
  level:
    org.hibernate.SQL: debug